### ISSUE TITLE
Error with save_genesets()

### ISSUE THREAD

**Issue by aswathyseb** [ftwkoopmans/goat#3]
I am running the example in the 'QuickStart' session but the command
 
 `save_genesets(result, genelist, filename = "goat.xlsx")`
 
 gives the error
 
 ```
Error in padj_sources && length(usource) > 1 : 
  invalid 'x' type in 'x && y'
```
I am using  R version 4.3.2.

**Comment by ftwkoopmans** [comment]
Thanks for reporting, will be fixed in the next release (coming days)

**Comment by ftwkoopmans** [comment]
I've updated the R package to beta version 0.9.4 , this should resolve the issue.

You can update your installation with the R command `pak::pkg_install("ftwkoopmans/goat", upgrade = FALSE)`  
(the latter parameter makes us skip optional updates)

**Comment by aswathyseb** [comment]
Hi,

May I ask you one more question? Is there a way to get mouse gene
sets using 'load_genesets_go_bioconductor'?

Thanks,

**Comment by ftwkoopmans** [comment]
Only human gene identifiers (from NCBI Entrez) are currently supported. If you have a genelist with mouse genes, I suggest mapping these to their respective human orthologs and then apply GOAT as per usual (genelist with human genes as input, use GOAT to load human genesets from GO).

Please open a new/separate GitHub issue for distinct topics/questions.
